include: package:lint/analysis_options.yaml

linter:
  rules:
    - parameter_assignments

analyzer:
  errors:
    sort_pub_dependencies: ignore
    use_setters_to_change_properties: ignore
    avoid_print: ignore
